# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=500)),
                ('meta_text', models.CharField(max_length=500)),
            ],
        ),
    ]
